-- Favorites table: links accounts to inventory items they've favorited
-- This is a "junction table" for a many-to-many relationship
CREATE TABLE IF NOT EXISTS public.favorites (
    favorite_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL,
    inv_id integer NOT NULL,
    date_added timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT favorites_pkey PRIMARY KEY (favorite_id),
    CONSTRAINT fk_account FOREIGN KEY (account_id)
        REFERENCES public.account (account_id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id)
        REFERENCES public.inventory (inv_id) ON DELETE CASCADE,
    CONSTRAINT unique_favorite UNIQUE (account_id, inv_id)
);
